### ISSUE TITLE
Dune Dynasty v1.6.0

### ISSUE THREAD

**Issue by codeflorist** [YuriyGuts/dunedynasty-macos#2]
hey yuriy,

i hope you are doing great!

i wanted to let you know, that i created a new fork of Dune Dynasty and released a new version (v1.6.0) [here](https://github.com/gameflorist/dunedynasty/releases/tag/v1.6.0). it includes many previously unreleased commits (incl. multiplayer!) by the original author (David Wang) as well as others. i also cherry picked your HiDPI commit (many thanks for that!), added in-game options for it and fixed/added a bunch of other stuff!

i only provide win32 and linux binaries however, and linked to your repo in my README for people looking for a Mac version.

feel free to merge these changes into your repo for a new Mac version! alternatively you could also fork your repo from mine to simplify future merges, or i'd also be glad to invite you as a collaborator to my fork, so you could maintain and provide the Mac-versions there. just let me know!

best wishes to you,
gerald

**Comment by racemus** [comment]
Hi guys,

It's the best Dune 2 port for macOS. Update it, please, please, please.

**Comment by codeflorist** [comment]
@racemus 

i've actually managed to compile a macOS version myself. i've just released v1.6.1 of Dune Dynasty with a macOS package provided:
https://github.com/gameflorist/dunedynasty/releases/tag/v1.6.1

it's only for Intel x86_64 Macs though. no Apple Silicon (M1) arm64 build ist provided.

let me know of any problems you have with it!

**Comment by racemus** [comment]
Cool!
I'll try it soon. Thanks a lot
